title: "Tom Cafarella"
# the subpath of your site, e.g. /blog
baseurl: ""
# the base hostname & protocol for your site. Don't let it end in '/' or you'll mess the links up
# Change for production:
url: "localhost:4000"

# Build settings
markdown: kramdown

#Handling Reading
encoding: "utf-8"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

pagination:
  permalink: pretty
  enabled: true
  per_page: 5
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 1
    after: 3
plugins:
  - jemoji
  - octopress-autoprefixer
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-admin
#  - jekyll-seo-tag

# Excludes
exclude:
  - .sass-cache
  - _site

sass:
  sass_dir: _sass
  style: :nested

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
tags:
  - Market Update
  - Real Estate
  - Home Buyer Tips
  - Home Seller Tips
