audit_header: false
title: Real Estate Investing Made Easy
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: 'Q and A Sessions'
    url: /QandA
  - title: Testimonials
    url: /testimonials
  - title: Our Team
    url: /our-team.html
  - title: Blog
    url: /blog  

client:
  name: Tom Cafarella
  license_number:
  about_markdown: |

  market:
  brand: Ocean City Development
  brokerage:
  address: 20 Delcarmine Street<br>Wakefield, MA 01880
  phone: 781-916-8800
  phone_type:
  phone2:
  phone2_type:
  email: tc@ocbuyshouse.com
  url: http://www.ocbuyshouses.com

CTAs:
  first_CTA_text: Register for a lunch and learn
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/
  VR_form:
highlights_header: I'm Here To Help You Succeed
highlights:
  - image: http://fillmurray.com/600/320
    title: This is a title
    text: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed odio vitae lacus elementum tincidunt non nec ipsum. Aliquam dictum lacus quam, sed iaculis ligula faucibus rhoncus. Nunc non velit vestibulum, porttitor lorem a, convallis ligula.
    cta: watch video
    url: http://google.com
  - image: http://fillmurray.com/600/320
    title: This is a title
    text: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed odio vitae lacus elementum tincidunt non nec ipsum. Aliquam dictum lacus quam, sed iaculis ligula faucibus rhoncus. Nunc non velit vestibulum, porttitor lorem a, convallis ligula.
    cta: watch video
    url: http://google.com
  - image: http://fillmurray.com/600/320
    title: This is a title
    text: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed odio vitae lacus elementum tincidunt non nec ipsum. Aliquam dictum lacus quam, sed iaculis ligula faucibus rhoncus. Nunc non velit vestibulum, porttitor lorem a, convallis ligula.
    cta: watch video
    url: http://google.com
sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: Jumpstart Your Real Estate Career
    CTA_text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed odio vitae lacus elementum tincidunt non nec ipsum. Aliquam dictum lacus quam, sed iaculis ligula faucibus rhoncus. Nunc non velit vestibulum, porttitor lorem a, convallis ligula.
    CTA_link_text: Join Our Team
    CTA_url: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title:
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  nav_logo_path: /img/navlogo.png
  hero_logo_path: /img/logo.png
  hero_logo_path_2: /img/logo2.png
  logo_width_number: 70
  hero_text: Real Estate Video Blog
  hero_background_hex: '#fff'
  hero_image_path: /img/background-gradient.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#005DAB'
  theme_color: '#f5f5f5'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: "transparent"

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
