audit_header: false
title: The Base Template
description: If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name:
  license_number:
  about_markdown: |

  market:
  brand:
  brokerage:
  address:
  phone:
  email:
  url:
  first_CTA_text: Home Evaluation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/
  VR_form:
welcome-text: |
  Each month we will send out two videos detailing what’s going on in our local real estate market. We’ll also discuss the latest market trends, the world of financing, and everything that’s happening in the real estate market. If you have any questions about real estate, let us know and we’ll answer you with a video.
socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title:
  categories: News & Politics
  image:
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author:
images:
  client_headshot_path: '/img/headshot.jpg'
  hero_logo_path: '/img/logo.png'
  hero_text: Real Estate Video Blog
  hero_background_hex: '#094264'
  hero_image_path: '/img/background.jpg'
brand_color: '#094264'
theme_color: '#094264'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'
